import { ButtonPrimaryS } from "@/components/Buttons/MainButtons";
import { api } from "@/utils/api";
import { type NextPage } from "next";
import Head from "next/head";
import { defaultBoards } from "@/data/defaultDataUpload";

const LoadDefaultData: NextPage = () => {
  const boardMutation = api.boards.createDefaultBoards.useMutation();

  const handleLoadDefaultData = async () => {
    await boardMutation.mutateAsync();
  };

  return (
    <>
      <Head>
        <title>Load default data</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen items-center justify-center">
        <ButtonPrimaryS
          onClick={() => {
            void handleLoadDefaultData();
          }}
        >
          load default data
        </ButtonPrimaryS>
      </main>
    </>
  );
};

export default LoadDefaultData;
